# config.yaml

# Base URL of the website to scrape
base_url: "https://example.com"

# HTTP headers to mimic real browser requests
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
  Accept-Language: "en-US,en;q=0.9"

# Data saving settings
data_saving:
  file_format: "csv"
  save_location: "data.csv"

# Retry logic settings
retry:
  max_retries: 3
  backoff_factor: 2

# Logging settings
logging:
  log_file: "scraper.log"
  log_level: "INFO"

# Missing data handling strategy
missing_data:
  strategy: "fill_mean"  # Options: drop, fill_mean, fill_median, fill_value
  fill_value: 0  # Used if strategy is 'fill_value'

# Visualization settings
visualization:
  output_dir: "./visualizations"
  types:
    - histogram
    - bar

# Optional settings
timeout: 10  # Request timeout (in seconds)
